/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaadvanced.coursework;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
